feat: stacking airdrop WIP
SelfKeyFoundation/Identity-Wallet pull request #2385
Opened 2020-09-09 17:40 UTC by sk91

2020-09-15 10:18 UTC, andregoncalves requested changes

2020-09-15 10:18 UTC, andregoncalves commented on src/renderer/kyc/kyc-card/kyc-card-container.jsx
> +				asked to provide more information by the service provider`,
This needs be generic

2020-09-16 14:34 UTC, sk91 commented on src/renderer/kyc/kyc-card/kyc-card-container.jsx
> +				asked to provide more information by the service provider`,
@andregoncalves fixed

2020-09-17 09:42 UTC, andregoncalves approved these changes
Great, looks good to me.

2020-09-17 09:50 UTC, merged